# Dependencies
highligher:       pygments
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'strikethrough']

# Permalinks
permalink:        pretty

# Setup
title:            Neal's Career Advice for Hackers
description:      Actionable and non-patronizing career advice for software developers
baseurl:          /advice
url:              https://nealshyam.com
siteurl:          "https://nealshyam.com/advice"
image:            https://nealshyam.com/img/headshot2.png

author:
  name:           'Neal Shyam'
  url:            https://nealshyam.com
  email:          neal@devpost.com
  twitter:        nealrs


plugins: ['jekyll-typogrify']

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nealrs/ns.com/

timezone:         America/New_York
TZ:               America/New_York
future: true
